version: '3.8'
services:
  cypress:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CYPRESS_baseUrl=https://www.venho.ai
      - CYPRESS_VIDEO=true
      - CYPRESS_reporter=spec
      - DEBUG=cypress:*
    command: npm run test:headless
