name: Playwright Tests

on:
  push:
    branches: [ main, feature/*, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        cd ada/qa-tests
        npm ci
    - name: Install Playwright Browsers
      run: |
        cd ada/qa-tests
        npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        cd ada/qa-tests
        npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ada/qa-tests/playwright-report/
        retention-days: 30
